# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Chloe
                                 A QGIS plugin
 The chloe history
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-11-08
        copyright            : (C) 2018 by Chloecompagny
        email                : Chloecompagny@Chloecompagny.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Jean-Charles Naud/Alkante'
__date__ = '2018-11-08'
__copyright__ = '(C) 2018 by Chloecompagny'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Chloe class from file Chloe.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .chloeplugin import ChloePlugin
    return ChloePlugin()
